workflows:
  ios-build:
    name: iOS Build for NavitsIDE
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_WORKSPACE: "NavitsIDE.xcworkspace"
        XCODE_SCHEME: "NavitsIDE"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install Dependencies
        script: |
          brew install cocoapods
          pod install

      - name: Build iOS App  
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE \
                     -scheme $XCODE_SCHEME \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $CM_BUILD_DIR/NavitsIDE.xcarchive

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "zachariahobie@outlook.com"
